<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'id'=>1,
                'name'=>'Đùi gà cay',
                'price'=>30000,
                'feature_image_path' => '/storage/product/1/hq8kQ0XExCGYSiRplskU.jpg',
                'content' => '<p>đ&ugrave;i g&agrave; sốt cay</p>',
                'category_id' => 5,
                'feature_image_name' => '1',
            ],
            [
                'id'=>2,
                'name'=>'Gà không xương sốt cay',
                'price'=>30000,
                'feature_image_path' => '1',
                'content' => '<p>Gà không xương sốt cay</p>',
                'category_id' => 5,
                'feature_image_name' => '0.jpg',
            ],
            [
                'id'=>3,
                'name'=>'Cánh gà sốt cay',
                'price'=>25000,
                'feature_image_path' => '1',
                'content' => '<p>Cánh gà sốt cay</p>',
                'category_id' => 5,
                'feature_image_name' => '1.jpg',
            ],
            [
                'id'=>4,
                'name'=>'Ức gà sốt cay',
                'price'=>30000,
                'feature_image_path' => '1',
                'content' => '<p>Ức gà sốt cay</p>',
                'category_id' => 5,
                'feature_image_name' => '2.jpg',
            ],
            [
                'id'=>5,
                'name'=>'Tỏi gà sốt cay',
                'price'=>25000,
                'feature_image_path' => '1',
                'content' => '<p>Tỏi gà sốt cay</p>',
                'category_id' => 5,
                'feature_image_name' => '3.jpg',
            ],
            [
                'id'=>6,
                'name'=>'Đùi gà chiên',
                'price'=>30000,
                'feature_image_path' => '1',
                'content' => '<p>Đ&ugrave;i g&agrave; chi&ecirc;n truyền thống k&egrave;m nước chấm</p>',
                'category_id' => 6,
                'feature_image_name' => '4.jpg',
            ],
            [
                'id'=>7,
                'name'=>'Tỏi gà chiên',
                'price'=>30000,
                'feature_image_path' => '1',
                'content' => '<p>Tỏi chi&ecirc;n truyền thống k&egrave;m nước chấm</p>',
                'category_id' => 6,
                'feature_image_name' => '5.jpg',
            ],
            [
                'id'=>8,
                'name'=>'Cánh gà chiên',
                'price'=>25000,
                'feature_image_path' => '1',
                'content' => '<p>Cánh g&agrave; chi&ecirc;n truyền thống k&egrave;m nước chấm</p>',
                'category_id' => 6,
                'feature_image_name' => '6.jpg',
            ],
            [
                'id'=>9,
                'name'=>'Ức gà chiên',
                'price'=>25000,
                'feature_image_path' => '1',
                'content' => '<p>Ức g&agrave; chi&ecirc;n truyền thống k&egrave;m nước chấm</p>',
                'category_id' => 6,
                'feature_image_name' => '7.jpg',
            ],
            [
                'id'=>10,
                'name'=>'Gà không xương',
                'price'=>30000,
                'feature_image_path' => '1',
                'content' => '<p> Gà không xương truyền thống k&egrave;m nước chấm</p>',
                'category_id' => 6,
                'feature_image_name' => '8.jpg',
            ],
            [
                'id'=>11,
                'name'=>'Pepsi',
                'price'=>10000,
                'feature_image_path' => 'https://bizweb.dktcdn.net/thumb/1024x1024/100/361/770/products/nuoc-ngot-pepsi-thai-lon-330ml.jpg?v=1570675810693',
                'content' => '	<p>Đồ uống</p>',
                'category_id' => 3,
                'feature_image_name' => '9.jpg',
            ],
            [
                'id'=>12,
                'name'=>'Fanta',
                'price'=>10000,
                'feature_image_path' => 'https://minhcaumart.vn/media/com_eshop/products/8935049510222.jpg',
                'content' => '	<p>Đồ uống</p>',
                'category_id' => 3,
                'feature_image_name' => '10.jpg',
            ],
            [
                'id'=>13,
                'name'=>'7UP',
                'price'=>10000,
                'feature_image_path' => 'https://bizweb.dktcdn.net/thumb/1024x1024/100/361/770/products/nuoc-ngot-7up-thai-lon-330ml.jpg?v=1570676100987',
                'content' => '	<p>Đồ uống</p>',
                'category_id' => 3,
                'feature_image_name' => '11.jpg',
            ],
            [
                'id'=>14,
                'name'=>'Salad khoai tây',
                'price'=>20000,
                'feature_image_path' => 'https://lh5.googleusercontent.com/86N3KNecCCGC3Xd_SfbA5BZJkbLj0O_YurenLGJLd3vKNTD7lkUAnaMcaj4Sk50DziCj6Plp9X5IMz65d2gq=w1366-h649-rw',
                'content' => '<p>Salad</p>',
                'category_id' => 7,
                'feature_image_name' => '12.jpg',
            ],
            [
                'id'=>15,
                'name'=>'Khoai tây chiên',
                'price'=>20000,
                'feature_image_path' => 'https://lh5.googleusercontent.com/86N3KNecCCGC3Xd_SfbA5BZJkbLj0O_YurenLGJLd3vKNTD7lkUAnaMcaj4Sk50DziCj6Plp9X5IMz65d2gq=w1366-h649-rw',
                'content' => '<p>Khoai tây chiên</p>',
                'category_id' => 7,
                'feature_image_name' => '13.jpg',
            ],
            [
                'id'=>16,
                'name'=>'Trứng cuộn kiểu Nhật',
                'price'=>20000,
                'feature_image_path' => 'https://lh5.googleusercontent.com/86N3KNecCCGC3Xd_SfbA5BZJkbLj0O_YurenLGJLd3vKNTD7lkUAnaMcaj4Sk50DziCj6Plp9X5IMz65d2gq=w1366-h649-rw',
                'content' => '<p>Trứng cuộn kiểu Nhật</p>',
                'category_id' => 7,
                'feature_image_name' => '14.jpg',
            ],
            [
                'id'=>17,
                'name'=>'Combo 4 người',
                'price'=>250000,
                'feature_image_path' => 'https://lh5.googleusercontent.com/86N3KNecCCGC3Xd_SfbA5BZJkbLj0O_YurenLGJLd3vKNTD7lkUAnaMcaj4Sk50DziCj6Plp9X5IMz65d2gq=w1366-h649-rw',
                'content' => '<p>Combo</p>',
                'category_id' => 8,
                'feature_image_name' => '15.jpg',
            ],
            [
                'id'=>18,
                'name'=>'Combo 2 người',
                'price'=>120000,
                'feature_image_path' => 'https://lh5.googleusercontent.com/86N3KNecCCGC3Xd_SfbA5BZJkbLj0O_YurenLGJLd3vKNTD7lkUAnaMcaj4Sk50DziCj6Plp9X5IMz65d2gq=w1366-h649-rw',
                'content' => '<p>Combo</p>',
                'category_id' => 8,
                'feature_image_name' => '16.jpg',
            ],
            [
                'id'=>19,
                'name'=>'Combo full jaja',
                'price'=>100000,
                'feature_image_path' => '1',
                'content' => '<p>Combo</p>',
                'category_id' => 8,
                'feature_image_name' => '17.jpg',
            ],
            [
                'id'=>20,
                'name'=>'Combo hủy diệt',
                'price'=>65000,
                'feature_image_path' => '1',
                'content' => '<p>Combo</p>',
                'category_id' => 9,
                'feature_image_name' => '18.jpg',
            ],
            [
                'id'=>21,
                'name'=>'Combo siêu khổng lồ',
                'price'=>1500000,
                'feature_image_path' => '1',
                'content' => '<p>Combo</p>',
                'category_id' => 9,
                'feature_image_name' => '19.jpg',
            ],
            [
                'id'=>22,
                'name'=>'Combo mới',
                'price'=>50000,
                'feature_image_path' => '1',
                'content' => '<p>Combo</p>',
                'category_id' => 9,
                'feature_image_name' => '20.jpg',
            ],
        ]);
    }
}